language: java
jdk:
   - oraclejdk8
addons:
   artifacts:
      path: '**/target/*.war'
before_script:
   - sudo apt-get update
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
   - mvn --version
