language: java
jdk:
   - oraclejdk8
deploy:
   provider: s3
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   access_key_id: $AWS_ACCESS_KEY_ID
   bucket: $ARTIFACTS_BUCKET
   skip_cleanup: true
   local_dir: build
   cache_control: "max-age=21600"
before_script:
   - sudo apt-get update
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
   - mvn --version
